# Generated by Django 3.1.1 on 2020-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_db', '0002_auto_20200906_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentry',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
