# Generated by Django 3.1.1 on 2020-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_db', '0003_auto_20200907_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentry',
            name='image',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
